# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField(blank=True, default=0)),
                ('longitud', models.IntegerField(blank=True, default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('weed', models.BooleanField(default=False)),
                ('comentario', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
