# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 03:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weed',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='weed',
            name='longitud',
        ),
        migrations.AddField(
            model_name='weed',
            name='geoLoc',
            field=django.contrib.gis.db.models.fields.PointField(default=0, srid=4326),
            preserve_default=False,
        ),
    ]
